### ISSUE TITLE
App Freezes when Delay Fastest is Selected

### ISSUE THREAD

**Issue by TouqeerAhmad** [rpng/android-dataset-recorder#1]
Hi, I would like to thank you for sharing this code with community, really very helpful. 

I have been trying data collection using this app, with a Samsung S8 phone. While the app works fine when I use any of the three IMU settings (Delay Normal, Delay UI and Delay Game), but when I try using Delay Fastest -- the app gets stuck. 

I wanted to run imu-vision sensor fusion offline with data collected from S8 and for that I was trying to get good frame rate for imu i.e. more number of frames between two vision samples. However, with Delay Game, I only get around 50 fps. 

I was wondering if you have any insights regarding this. 

Thanks, 
Touqeer

**Comment by goldbattle** [comment]
I would look into how that setting is getting set, I think I remember back when I made this it had a higher rate then 50fps for the IMU. I never fully tested this package out as I ended up not needing it for my project. Here are the points in the code I would look at:

[HERE](https://github.com/rpng/android-dataset-recorder/blob/master/app/src/main/java/io/rpng/recorder/managers/IMUManager.java#L139-L140) and [HERE](https://github.com/rpng/android-dataset-recorder/blob/fb9cd6b0b1492b06f4899fc42af9a0f8ba79cda1/app/src/main/res/values/arrays.xml#L17-L22)



From the looks of it, I am hard coding the values of the ENUM that should be getting used.
https://developer.android.com/reference/android/hardware/SensorManager.html#SENSOR_DELAY_FASTEST

Ideally that should work, but maybe there is some issues that we are not aware of?
Not sure, hope this helps you look in the right direction.

**Comment by TouqeerAhmad** [comment]
Thank you for your detailed reply. I was actually able to get the required data (with 20fps vision and 100 fps imu) by explicitly specifying the sample rate as advised in here.

https://stackoverflow.com/questions/17663191/android-accelerometer-sampling-rate

The weird thing is for Pixel2/Pixel2XL the default DelayFastest worked but for S8/Pixel and PixelXL, I had to specify the sampling rate, the flag for DelayFastest was making it stuck.

Thank you for you help and code!

**Comment by goldbattle** [comment]
Might have been since it wasn't being set as an ENUM it was being taken as
a zero microsecond time between sensor readings (which I assume would
causes a lot of things to break).
Glad you found your fix.

**Comment by fangxu622** [comment]
do you  solve the problem ? I get the problem in lenovo phab2 pro(google tango phone). App Freezes when Delay Fastest is Selected..and I can get 90-100 fps imu  when select delay game ,but the vision data just have 3-5fps, I want to get 20fps vision and 100 fps imu or higher~~how do you  solve this problem

**Comment by goldbattle** [comment]
The problem with the vision data is that it needs to get copied into an opencv format which I think causes the largest amount of delay and thus a slow framerate. I was only able to have higher framerates if I used an extremely small images. You could try to optimize/investigate this section of code:
https://github.com/rpng/android-dataset-recorder/blob/master/app/src/main/java/io/rpng/recorder/activities/MainActivity.java#L187-L290

For the IMU, you could manually change the code so that you are inputting "10" for 10 milliseconds which is the delay for 100hz. (see https://stackoverflow.com/a/21427536)

**Comment by fangxu622** [comment]
@goldbattle  why not record video for vision data avoid app get stuck? Can we do that?
