### ISSUE TITLE
Gradle sync failed: Exception thrown while executing model rule: NdkComponentModelPlugin.Rules#createNativeBuildModel

### ISSUE THREAD

**Issue by srikar8** [rpng/android-dataset-recorder#2]
Am getting this error when I am running the project.
thank you in advance.

**Comment by goldbattle** [comment]
Not sure what the issue is, would make sure you have NDK installed, and android studio updated.
I would google to see if anybody else has had this issue.

**Comment by srikar8** [comment]
solved from this link
https://stackoverflow.com/questions/47057160/gradle-sync-failed-exception-thrown-while-executing-model-rule-basecomponentmo

thank you so much.
